"""Append-only audit log of story-state changes.

One row per significant change to a story or its articles: HITL
decisions, clustering attaches/orphans, freeze/archive transitions,
field-level edits, feedback resolutions. Read by the /dashboard/learning
page and the auto-maintenance feedback canaries.

Created via the self-heal DDL in app/main.py (CREATE TABLE IF NOT
EXISTS) since the original implementation predated the formal model.
This file documents the schema for tooling (autogenerated migrations,
type checking, IDE refs) without changing the existing table.

Append-only by convention: nothing in the codebase issues a DELETE
against this table. Retention will be enforced by a future maintenance
step (project_war_audit_2026-05-03 item J).
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class StoryEvent(Base):
    __tablename__ = "story_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )

    # Optional FKs — events may apply to a story, an article, or both.
    # Both nullable so we can log decisions about an article BEFORE it's
    # been attached to any story (e.g., orphan rehome candidates).
    story_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True, index=True,
    )
    article_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True, index=True,
    )

    # Categorical event type — used by the dashboard's filter and the
    # canary queries. Examples (not exhaustive):
    #   feedback_orphan_rater, feedback_orphan_anon, feedback_rehome,
    #   feedback_summary_regen, feedback_niloofar_orphan,
    #   feedback_niloofar_dismiss, cluster_block_negative,
    #   cluster_block_low_trust, source_trust_change,
    #   story_umbrella_demoted, story_split_candidate.
    event_type: Mapped[str] = mapped_column(String(40), nullable=False, index=True)

    # Who triggered the event:
    #   "rater" — trusted human via /rate
    #   "anon" — unauthenticated visitor via /improve
    #   "niloofar" — Claude-driven editorial audit
    #   "maintenance" — auto-pipeline step
    #   "admin" — manual admin action via dashboard
    actor: Mapped[str] = mapped_column(String(40), nullable=False)

    # For field-level edits, which column changed (e.g. "title_fa",
    # "summary_fa", "priority"). Null for non-field events.
    field: Mapped[str | None] = mapped_column(String(60), nullable=True)
    old_value: Mapped[str | None] = mapped_column(Text, nullable=True)
    new_value: Mapped[str | None] = mapped_column(Text, nullable=True)

    # 0..1 confidence score for LLM-driven events; null for human or
    # deterministic events.
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Free-form context: cosine value, article counts, source slugs,
    # rater id, threshold values — anything the dashboard might want
    # to render alongside the event. JSONB so the taxonomy can grow.
    signals: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<StoryEvent {self.event_type} by {self.actor} "
            f"story={self.story_id} field={self.field}>"
        )
