"""Weekly worldview synthesis, one row per (bundle, window).

A worldview digest describes what the OUTLETS in a given 4-subgroup
bundle (principlist, reformist, moderate_diaspora, radical_diaspora)
told their readers over a 7-day window. Not "what readers of this
group believe" — always outlet-level. The caveat is baked into the
data contract so the UI can't accidentally drift into stereotyping.

Generated by app.services.worldview_digest.generate_worldview_digests,
run weekly by auto_maintenance.step_worldview_digests. Read by the
/api/v1/worldviews/* endpoints.
"""

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, Float, Integer, String, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class WorldviewDigest(Base):
    __tablename__ = "worldview_digests"
    __table_args__ = (
        UniqueConstraint("bundle", "window_start", name="uq_worldview_bundle_window"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # One of: principlist | reformist | moderate_diaspora | radical_diaspora.
    # Mirrors narrative_groups.NarrativeGroup so the mapping stays a
    # single source of truth.
    bundle: Mapped[str] = mapped_column(String(24), nullable=False)

    # Inclusive-exclusive window: [window_start, window_end). Stored as
    # DATE so a "this week" lookup can use equality against the Monday
    # of the target week without timezone fuzz.
    window_start: Mapped[date] = mapped_column(Date, nullable=False)
    window_end: Mapped[date] = mapped_column(Date, nullable=False)

    # "ok" when synthesis_fa is populated. "insufficient" when the
    # bundle missed a precondition (too few articles, too few sources,
    # bias-analysis coverage too low). UI shows an explicit
    # "not enough signal" card in that case rather than hiding it —
    # a quiet week should read as quiet, not as an outage.
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="ok")

    # LLM output, structured. Schema:
    #   {
    #     "core_beliefs":       [{text, article_count, source_count, example_article_ids}],
    #     "emphasized":         [{topic, frequency, sample_article_ids}],
    #     "absent":             [{topic, other_bundles_covering, note}],
    #     "tone_profile":       {dominant, alt, examples},
    #     "predictions_primed": [{text, article_count}],
    #   }
    # Every belief MUST carry an article_count ≥ 3 and reference
    # ≥ 2 sources — enforced by the synthesis prompt + a post-LLM
    # validator. Anything below the floor is dropped before storage.
    synthesis_fa: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Citation chain. {belief_key: [article_id, ...]} mapping so the
    # UI can click any belief on the card and expand the exact articles
    # that backed it — the grounding promise is that every claim has
    # a source trail the reader can verify.
    evidence_fa: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Measurement fields the /lab page surfaces in the card footer so
    # readers can see the signal strength behind the synthesis.
    article_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    source_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    coverage_pct: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Cost/provenance — what model synthesized this, and how much did
    # it cost. Dashboard filters llm_usage_logs by purpose='worldview_digest'
    # for the canonical ledger; this field is a convenience mirror.
    model_used: Mapped[str | None] = mapped_column(String(80), nullable=True)
    token_cost_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return (
            f"<WorldviewDigest {self.bundle} "
            f"{self.window_start}..{self.window_end} "
            f"status={self.status} n={self.article_count}>"
        )
