"""add analyst_json and image_url to topics

Revision ID: 225d1a5e311f
Revises: 6f0c2571cf5e
Create Date: 2026-04-09 08:47:14.642072
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '225d1a5e311f'
down_revision: Union[str, None] = '6f0c2571cf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('analyst_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('topics', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'image_url')
    op.drop_column('topics', 'analyst_json')
    # ### end Alembic commands ###
