"""add media_dimensions to sources

Revision ID: 4d99807e3652
Revises: 225d1a5e311f
Create Date: 2026-04-10 01:04:56.006672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '4d99807e3652'
down_revision: Union[str, None] = '225d1a5e311f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('media_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'media_dimensions')
    # ### end Alembic commands ###
