"""add topics and topic_articles tables

Revision ID: 6f0c2571cf5e
Revises: 003
Create Date: 2026-04-09 07:42:25.470281
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '6f0c2571cf5e'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_fa', sa.Text(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description_fa', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('analysis_fa', sa.Text(), nullable=True),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('topic_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Junction table linking topics to articles'
    )
    op.create_index(op.f('ix_topic_articles_article_id'), 'topic_articles', ['article_id'], unique=False)
    op.create_index(op.f('ix_topic_articles_topic_id'), 'topic_articles', ['topic_id'], unique=False)
    op.alter_column('articles', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bias_scores', 'political_alignment',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='-1 pro-regime to +1 opposition',
               existing_nullable=True)
    op.alter_column('bias_scores', 'tone_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='-1 negative to +1 positive',
               existing_nullable=True)
    op.alter_column('bias_scores', 'emotional_language_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0 factual to 1 loaded',
               existing_nullable=True)
    op.alter_column('bias_scores', 'scoring_method',
               existing_type=sa.VARCHAR(length=20),
               comment='llm_initial | llm_refined | crowd_validated',
               existing_nullable=False)
    op.alter_column('bias_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_bias_article'), table_name='bias_scores')
    op.create_index(op.f('ix_bias_scores_article_id'), 'bias_scores', ['article_id'], unique=False)
    op.alter_column('community_ratings', 'political_alignment_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='-2 to +2',
               existing_nullable=True)
    op.alter_column('community_ratings', 'factuality_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='1-5',
               existing_nullable=True)
    op.alter_column('community_ratings', 'tone_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='-2 to +2',
               existing_nullable=True)
    op.alter_column('community_ratings', 'emotional_language_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='1-5',
               existing_nullable=True)
    op.alter_column('community_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_community_ratings_article_id'), 'community_ratings', ['article_id'], unique=False)
    op.create_index(op.f('ix_community_ratings_user_id'), 'community_ratings', ['user_id'], unique=False)
    op.alter_column('ingestion_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='success | error | partial',
               existing_nullable=False)
    op.create_index(op.f('ix_ingestion_log_source_id'), 'ingestion_log', ['source_id'], unique=False)
    op.alter_column('rater_feedback', 'suggested_factional',
               existing_type=sa.VARCHAR(length=20),
               comment='hardline | principlist | reformist | moderate | opposition | monarchist | left',
               existing_nullable=True)
    op.alter_column('rater_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_sentiment_snapshots', 'framing_distribution',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{"conflict": 5, "human_rights": 3, ...}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('social_sentiment_snapshots', 'narrative_divergence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0-1: how much social media framing differs from news media framing',
               existing_nullable=True)
    op.alter_column('social_sentiment_snapshots', 'snapshot_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_social_sentiment_snapshots_story_id'), 'social_sentiment_snapshots', ['story_id'], unique=False)
    op.alter_column('sources', 'state_alignment',
               existing_type=sa.VARCHAR(length=20),
               comment='state | semi_state | independent | diaspora',
               existing_nullable=False)
    op.alter_column('sources', 'production_location',
               existing_type=sa.VARCHAR(length=20),
               comment='inside_iran | outside_iran',
               existing_nullable=False)
    op.alter_column('sources', 'factional_alignment',
               existing_type=sa.VARCHAR(length=20),
               comment='hardline | principlist | reformist | moderate | opposition | monarchist | left',
               existing_nullable=True)
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('sources_slug_key'), 'sources', type_='unique')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.alter_column('stories', 'blindspot_type',
               existing_type=sa.VARCHAR(length=20),
               comment='state_only | diaspora_only | single_source',
               existing_nullable=True)
    op.alter_column('stories', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Manual priority: higher = more prominent. 0=auto',
               existing_server_default=sa.text('0'))
    op.alter_column('stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('stories_slug_key'), 'stories', type_='unique')
    op.drop_index(op.f('ix_stories_slug'), table_name='stories')
    op.create_index(op.f('ix_stories_slug'), 'stories', ['slug'], unique=True)
    op.alter_column('telegram_channels', 'channel_type',
               existing_type=sa.VARCHAR(length=20),
               comment='news | commentary | activist | political_party | citizen | aggregator',
               existing_nullable=False)
    op.alter_column('telegram_channels', 'political_leaning',
               existing_type=sa.VARCHAR(length=20),
               comment='pro_regime | reformist | opposition | monarchist | left | neutral',
               existing_nullable=True)
    op.alter_column('telegram_channels', 'last_message_id',
               existing_type=sa.INTEGER(),
               comment='Telegram message ID of last fetched post',
               existing_nullable=True)
    op.alter_column('telegram_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('telegram_channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('telegram_channels_username_key'), 'telegram_channels', type_='unique')
    op.create_index(op.f('ix_telegram_channels_username'), 'telegram_channels', ['username'], unique=True)
    op.alter_column('telegram_posts', 'sentiment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='-1 negative to +1 positive',
               existing_nullable=True)
    op.alter_column('telegram_posts', 'shares_news_link',
               existing_type=sa.BOOLEAN(),
               comment='Post contains a link to a known news article',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_posts', 'is_commentary',
               existing_type=sa.BOOLEAN(),
               comment='Post is commentary/analysis rather than news sharing',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_telegram_posts_channel_id'), 'telegram_posts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_telegram_posts_story_id'), 'telegram_posts', ['story_id'], unique=False)
    op.alter_column('users', 'rater_level',
               existing_type=sa.VARCHAR(length=20),
               comment='novice | trained | expert | admin',
               existing_nullable=False,
               existing_server_default=sa.text("'novice'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'rater_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='novice | trained | expert | admin',
               existing_nullable=False,
               existing_server_default=sa.text("'novice'::character varying"))
    op.drop_index(op.f('ix_telegram_posts_story_id'), table_name='telegram_posts')
    op.drop_index(op.f('ix_telegram_posts_channel_id'), table_name='telegram_posts')
    op.alter_column('telegram_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telegram_posts', 'is_commentary',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Post is commentary/analysis rather than news sharing',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_posts', 'shares_news_link',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Post contains a link to a known news article',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_posts', 'sentiment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='-1 negative to +1 positive',
               existing_nullable=True)
    op.drop_index(op.f('ix_telegram_channels_username'), table_name='telegram_channels')
    op.create_unique_constraint(op.f('telegram_channels_username_key'), 'telegram_channels', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('telegram_channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telegram_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telegram_channels', 'last_message_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Telegram message ID of last fetched post',
               existing_nullable=True)
    op.alter_column('telegram_channels', 'political_leaning',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pro_regime | reformist | opposition | monarchist | left | neutral',
               existing_nullable=True)
    op.alter_column('telegram_channels', 'channel_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='news | commentary | activist | political_party | citizen | aggregator',
               existing_nullable=False)
    op.drop_index(op.f('ix_stories_slug'), table_name='stories')
    op.create_index(op.f('ix_stories_slug'), 'stories', ['slug'], unique=False)
    op.create_unique_constraint(op.f('stories_slug_key'), 'stories', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('stories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stories', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Manual priority: higher = more prominent. 0=auto',
               existing_server_default=sa.text('0'))
    op.alter_column('stories', 'blindspot_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='state_only | diaspora_only | single_source',
               existing_nullable=True)
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=False)
    op.create_unique_constraint(op.f('sources_slug_key'), 'sources', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'factional_alignment',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='hardline | principlist | reformist | moderate | opposition | monarchist | left',
               existing_nullable=True)
    op.alter_column('sources', 'production_location',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='inside_iran | outside_iran',
               existing_nullable=False)
    op.alter_column('sources', 'state_alignment',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='state | semi_state | independent | diaspora',
               existing_nullable=False)
    op.drop_index(op.f('ix_social_sentiment_snapshots_story_id'), table_name='social_sentiment_snapshots')
    op.alter_column('social_sentiment_snapshots', 'snapshot_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_sentiment_snapshots', 'narrative_divergence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0-1: how much social media framing differs from news media framing',
               existing_nullable=True)
    op.alter_column('social_sentiment_snapshots', 'framing_distribution',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"conflict": 5, "human_rights": 3, ...}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('rater_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rater_feedback', 'suggested_factional',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='hardline | principlist | reformist | moderate | opposition | monarchist | left',
               existing_nullable=True)
    op.drop_index(op.f('ix_ingestion_log_source_id'), table_name='ingestion_log')
    op.alter_column('ingestion_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='success | error | partial',
               existing_nullable=False)
    op.drop_index(op.f('ix_community_ratings_user_id'), table_name='community_ratings')
    op.drop_index(op.f('ix_community_ratings_article_id'), table_name='community_ratings')
    op.alter_column('community_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_ratings', 'emotional_language_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='1-5',
               existing_nullable=True)
    op.alter_column('community_ratings', 'tone_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='-2 to +2',
               existing_nullable=True)
    op.alter_column('community_ratings', 'factuality_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='1-5',
               existing_nullable=True)
    op.alter_column('community_ratings', 'political_alignment_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='-2 to +2',
               existing_nullable=True)
    op.drop_index(op.f('ix_bias_scores_article_id'), table_name='bias_scores')
    op.create_index(op.f('idx_bias_article'), 'bias_scores', ['article_id'], unique=False)
    op.alter_column('bias_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bias_scores', 'scoring_method',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='llm_initial | llm_refined | crowd_validated',
               existing_nullable=False)
    op.alter_column('bias_scores', 'emotional_language_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0 factual to 1 loaded',
               existing_nullable=True)
    op.alter_column('bias_scores', 'tone_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='-1 negative to +1 positive',
               existing_nullable=True)
    op.alter_column('bias_scores', 'political_alignment',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='-1 pro-regime to +1 opposition',
               existing_nullable=True)
    op.alter_column('articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('articles', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_topic_articles_topic_id'), table_name='topic_articles')
    op.drop_index(op.f('ix_topic_articles_article_id'), table_name='topic_articles')
    op.drop_table('topic_articles')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
