"""perf indexes + server_defaults + story_event model formalization

Revision ID: v7q8r9s0t1u2
Revises: u6p7q8r9s0t1
Create Date: 2026-05-03 09:00:00.000000

Why (Parham 2026-05-03 audit):
1. Hot WHERE/ORDER BY columns lacked indexes — sequential scans on
   stories and articles became visible bottlenecks once the row count
   grew past ~25K articles / ~1300 stories. Fixed by adding 9 partial
   and full indexes that match the trending API + clustering query
   patterns exactly.
2. Several Story / Article columns had Python-side `default=` but no
   `server_default=`, so out-of-band INSERTs (direct SQL, webhook
   ingestion, manual seeds) got NULL instead of the intended value —
   crashing downstream `view_count + 1` style updates with TypeError.
   Fixed by adding ALTER COLUMN SET DEFAULT and backfilling NULLs to 0.
3. The `story_events` table existed (created by app/main.py self-heal)
   but had no Python model file — autogenerated migrations would have
   recreated it, alembic --sql would have flagged it as missing. Now
   the model lives at app/models/story_event.py; this migration is a
   no-op for the table itself but documents the chain.

Idempotent: the same DDL is applied at FastAPI startup via the
self-heal block in app/main.py. This migration is for traceability +
fresh-DB bootstrap; production already has these objects from the
self-heal path.
"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "v7q8r9s0t1u2"
down_revision = "u6p7q8r9s0t1"
branch_labels = None
depends_on = None


_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_stories_trending_rank ON stories(priority DESC, trending_score DESC) WHERE archived_at IS NULL",
    "CREATE INDEX IF NOT EXISTS idx_stories_first_published ON stories(first_published_at DESC NULLS LAST)",
    "CREATE INDEX IF NOT EXISTS idx_stories_last_updated ON stories(last_updated_at DESC NULLS LAST)",
    "CREATE INDEX IF NOT EXISTS idx_stories_frozen_at_set ON stories(frozen_at) WHERE frozen_at IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_stories_blindspot ON stories(is_blindspot, archived_at) WHERE is_blindspot = TRUE",
    "CREATE INDEX IF NOT EXISTS idx_articles_processed_null ON articles(ingested_at DESC) WHERE processed_at IS NULL",
    "CREATE INDEX IF NOT EXISTS idx_articles_embedding_null_recent ON articles(ingested_at DESC) WHERE embedding IS NULL",
    "CREATE INDEX IF NOT EXISTS idx_articles_story ON articles(story_id) WHERE story_id IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_sources_content_filters ON sources USING GIN (content_filters)",
]

_DEFAULTS = [
    "ALTER TABLE articles ALTER COLUMN cluster_attempts SET DEFAULT 0",
    "ALTER TABLE stories ALTER COLUMN view_count SET DEFAULT 0",
    "ALTER TABLE stories ALTER COLUMN article_count SET DEFAULT 0",
    "ALTER TABLE stories ALTER COLUMN source_count SET DEFAULT 0",
    "ALTER TABLE stories ALTER COLUMN priority SET DEFAULT 0",
    "ALTER TABLE stories ALTER COLUMN trending_score SET DEFAULT 0",
]

_BACKFILLS = [
    "UPDATE articles SET cluster_attempts = 0 WHERE cluster_attempts IS NULL",
    "UPDATE stories SET view_count = 0 WHERE view_count IS NULL",
    "UPDATE stories SET article_count = 0 WHERE article_count IS NULL",
    "UPDATE stories SET source_count = 0 WHERE source_count IS NULL",
    "UPDATE stories SET priority = 0 WHERE priority IS NULL",
    "UPDATE stories SET trending_score = 0 WHERE trending_score IS NULL",
]


def upgrade() -> None:
    for stmt in _INDEXES + _DEFAULTS + _BACKFILLS:
        op.execute(stmt)


def downgrade() -> None:
    # Indexes are safe to drop on downgrade. Defaults stay (dropping a
    # default doesn't change existing rows). NULL-backfill is not
    # reversed (no information about which rows were originally NULL).
    op.execute("DROP INDEX IF EXISTS idx_stories_trending_rank")
    op.execute("DROP INDEX IF EXISTS idx_stories_first_published")
    op.execute("DROP INDEX IF EXISTS idx_stories_last_updated")
    op.execute("DROP INDEX IF EXISTS idx_stories_frozen_at_set")
    op.execute("DROP INDEX IF EXISTS idx_stories_blindspot")
    op.execute("DROP INDEX IF EXISTS idx_articles_processed_null")
    op.execute("DROP INDEX IF EXISTS idx_articles_embedding_null_recent")
    op.execute("DROP INDEX IF EXISTS idx_articles_story")
    op.execute("DROP INDEX IF EXISTS idx_sources_content_filters")
