/**
 * دورنما — flowing-prose synthesis above the bias panel.
 *
 * Renders only when the briefing exists (top-N trending stories only,
 * generated by backend/app/services/doornama.py). On long-tail stories
 * the component returns null so the page collapses cleanly.
 *
 * Voice: integrative narrator. Reader scans this paragraph for the
 * "what's happening" gist before drilling into bias_explanation_fa or
 * the per-side narrative tabs in StoryAnalysisPanel.
 */
export default function DoornamaBriefing({ briefing }: { briefing: string | null | undefined }) {
  if (!briefing || !briefing.trim()) return null;

  return (
    <div
      dir="rtl"
      className="mb-4 border-r-[3px] border-slate-900 dark:border-slate-100 bg-slate-50 dark:bg-slate-900/40 px-5 py-4"
    >
      <h3 className="text-[13px] font-black tracking-wide text-slate-700 dark:text-slate-300 mb-2">
        دورنما
      </h3>
      <p className="text-[15px] leading-8 text-slate-800 dark:text-slate-200 whitespace-pre-line">
        {briefing}
      </p>
    </div>
  );
}
